# Generated by Django 5.1.6 on 2025-02-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ice_cream", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="icecream",
            options={"verbose_name": "мороженое", "verbose_name_plural": "Мороженое"},
        ),
        migrations.AlterModelOptions(
            name="topping",
            options={"verbose_name": "топпинги", "verbose_name_plural": "Топпинги"},
        ),
        migrations.AlterModelOptions(
            name="wrapper",
            options={"verbose_name": "обёртки", "verbose_name_plural": "Обёртки"},
        ),
        migrations.AddField(
            model_name="icecream",
            name="output_order",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AddField(
            model_name="icecream",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wrapper",
            name="title",
            field=models.CharField(
                help_text="Уникальное название обёртки, не более 256 символов",
                max_length=256,
            ),
        ),
    ]
